name: Go
env:
  GO_VERSION: 1.20
  APP_NAME: foo
run-name: "${{ github.run_id }}: Workflow run by @${{ github.actor }}"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "${{ env.GO_VERSION }}"
    - name: Build
      run: go build -v -o ${APP_NAME} main.go
    - name: Test
      run: test -f ${APP_NAME}
