name: Go
env:
  GO_VERSION: 1.20
run-name: "${{ github.run_id }}: Workflow run by @${{ github.actor }}"
on:
  workflow_dispatch: {}
  push:
    branches: [ "main", "dev" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
    - name: "Set Up Go Environment"
      uses: actions/setup-go@v4
      with:
        go-version: "${{ env.GO_VERSION }}"
    - name: "Run Go Tests"
      run: go test -v main.go main_test.go
